services:
  longfor-signin:
    image: ghcr.io/langchou/newlongfor:latest
    container_name: longfor
    restart: unless-stopped
    ports:
      - "5900:5900"
    env_file:
      - .env  # 直接加载.env文件
    environment:
      - FLASK_ENV=production
      - TURNSTILE_ENABLED=${TURNSTILE_ENABLED:-false}
      - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY:-}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY:-}
    volumes:
      - ./data:/app/data  # 数据目录
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5900/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s